current nulldriver state

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -16,8 +16,6 @@ if [ -z "$working_dir" ]; then
   exit 1
 fi
 
-cd "$working_dir"
-
 # for jq
 PATH=/usr/local/bin:$PATH:.
 
@@ -47,61 +45,27 @@ cf_dial_timeout=$(jq -r '.source.cf_dial_timeout //empty' < $payload) && [ -n "$
 cf_trace=$(jq -r '.source.cf_trace //empty' < $payload) && echo "$cf_trace" | grep -qi 'true' && export CF_TRACE=true
 command_file=$(echo "$params" | jq -r '.command_file //empty')
 
-cf_home=$(jq -r '.params.cf_home // .source.cf_home // empty' < $payload)
-
-if [ -n "$cf_home" ]; then
-    export CF_HOME=$cf_home
-    export CF_PLUGIN_HOME=$HOME
-
-    if ! cf_is_logged_in; then
-      printf '\e[91m[ERROR]\e[0m not logged in to cf (check %s/config.json)\n' $CF_HOME
-      exit 1
-    fi
-
-    api=$(cat $CF_HOME/.cf/config.json | jq -r .Target)
-
-    if [ -z "$source_org" ]; then
-        source_org=$(cat $CF_HOME/.cf/config.json | jq -r .OrganizationFields.Name)
-    fi
-
-    if [ -z "$source_space" ]; then
-        source_space=$(cat $CF_HOME/.cf/config.json | jq -r .SpaceFields.Name)
-    fi
-
-else
-    if [ -z "$api" ]; then
-      printf '\e[91m[ERROR]\e[0m invalid payload (missing api)\n'
-      exit 1
-    fi
-
-    if [ -n "$username" ] && [ -n "$client_id" ]; then
-      printf '\e[91m[ERROR]\e[0m invalid payload (must specify only username or client_id)\n'
-      exit 1
-    fi
-
-    if [ -n "$username" ] && [ -z "$password" ]; then
-      printf '\e[91m[ERROR]\e[0m invalid payload (missing password)\n'
-      exit 1
-    fi
-
-    if [ -n "$client_id" ] && [ -z "$client_secret" ]; then
-      printf '\e[91m[ERROR]\e[0m invalid payload (missing client_secret)\n'
-      exit 1
-    fi
-
-    # Login with credentials
-    cf_api "$api" "$skip_cert_check"
-    if [ -n "$client_id" ]; then
-      cf_auth_client "$client_id" "$client_secret"
-    else
-      cf_auth_user "$username" "$password" "$origin"
-    fi
-
-    if ! cf_is_logged_in; then
-      printf '\e[91m[ERROR]\e[0m not logged in to cf (check your credentials)\n'
-      exit 1
-    fi
+if [ -z "$api" ]; then
+  printf '\e[91m[ERROR]\e[0m invalid payload (missing api)\n'
+  exit 1
 fi
+
+if [ -n "$username" ] && [ -n "$client_id" ]; then
+  printf '\e[91m[ERROR]\e[0m invalid payload (must specify only username or client_id)\n'
+  exit 1
+fi
+
+if [ -n "$username" ] && [ -z "$password" ]; then
+  printf '\e[91m[ERROR]\e[0m invalid payload (missing password)\n'
+  exit 1
+fi
+
+if [ -n "$client_id" ] && [ -z "$client_secret" ]; then
+  printf '\e[91m[ERROR]\e[0m invalid payload (missing client_secret)\n'
+  exit 1
+fi
+
+cd "$working_dir"
 
 if [ -n "$command_file" ]; then
   if [ -r "$command_file" ]; then
@@ -114,6 +78,8 @@ if [ -n "$command_file" ]; then
 fi
 
 printf '\e[92m[INFO]\e[0m %s\n' "$(cf version)"
+
+cf_logged_in=false
 
 # convert the single command into a single element array
 if echo $params | jq -e 'has("command")' >/dev/null; then
@@ -136,6 +102,15 @@ echo "$params" | jq -c '.commands[]' | while read -r options; do
   org=$(echo $options | jq -r '.org //empty') && [ -z "$org" ] && org=$source_org
   space=$(echo $options | jq -r '.space //empty') && [ -z "$space" ] && space=$source_space
 
+  if ! $cf_logged_in; then
+    cf_api "$api" "$skip_cert_check"
+    if [ -n "$client_id" ]; then
+      cf_auth_client "$client_id" "$client_secret"
+    else
+      cf_auth_user "$username" "$password" "$origin"
+    fi
+    cf_logged_in=true
+  fi
 
   if [ "create-org" = "$command" ]; then
     printf '\e[92m[INFO]\e[0m Executing \e[33m%s\e[0m: %s\n' "$command" "$org"
@@ -364,37 +339,34 @@ echo "$params" | jq -c '.commands[]' | while read -r options; do
     path=$(echo $options | jq -r '.path //empty')
     current_app_name=$(echo $options | jq -r '.current_app_name //empty')
     environment_variables=$(echo $options | jq -r '.environment_variables //empty')
+    stack=$(echo $options | jq -r '.stack //empty')
 
     if [ ! -f "$manifest" ]; then
       printf '\e[91m[ERROR]\e[0m invalid payload (manifest is not a file: %s)\n' "$manifest"
       exit 1
     fi
 
-    instructions="$(dirname $manifest)/.cf-cli-resource-manifest-update-instructions.yml"
-
-    # add pipeline defined environment variables to the manifest
-    for key in $(echo $environment_variables | jq -r 'keys[]');
-    do
-      value=$(echo $environment_variables | jq -r --arg key "$key" '.[$key]')
-      # valid inline yaml (flow style) so quote the value if it starts with a sequence or map
-      if [[ "$value" == [* || "$value" == {* ]]; then
-        echo "env.$key: '$value'" >>"$instructions"
-      else
-        echo "env.$key: $value" >>"$instructions"
-      fi
-    done
-
-    if [ -f "$instructions" ]; then
-      mv "$manifest" "$manifest.original"
-      yq w -s "$instructions" "$manifest.original" > "$manifest"
+    if [ -n "$environment_variables" ]; then
+      cp "$manifest" "$manifest.original"
+      for key in $(echo $environment_variables | jq -r 'keys[]'); do
+        value=$(echo $environment_variables | jq -r --arg key "$key" '.[$key]')
+        yq w -i "$manifest" -- "env.$key" "$value"
+      done
     fi
 
-    args="-f $manifest"
-    [ -n "$path" ] && args="$args -p $path"
+    args=(-f "$manifest")
+    [ -n "$path" ]  && args+=(-p $path) # don't quote so we can support globbing
+    [ -n "$stack" ] && args+=(-s "$stack")
 
     printf '\e[92m[INFO]\e[0m Executing \e[33m%s\e[0m: %s\n' "$command" "$current_app_name"
     cf_target "$org" "$space"
-    cf_zero_downtime_push "$args" "$current_app_name"
+
+    if [ -n "$current_app_name" ]; then
+      # autopilot (tested v0.0.2 - v0.0.6) doesn't like CF_TRACE=true
+      CF_TRACE=false cf zero-downtime-push "$current_app_name" "${args[@]}"
+    else
+      cf push "${args[@]}"
+    fi
   elif [ "set-env" = "$command" ]; then
     app_name=$(echo $options | jq -r '.app_name //empty')
     env_var_name=$(echo $options | jq -r '.env_var_name //empty')
